Src/BugTracker/Interface.Presentation/Controllers/HomeController.cs
using BugTracker.Domain.Entity;
using BugTracker.Domain.Interface.Service;
using Interface.Presentation.Mail_Body;
using Interface.Presentation.Models.User;
using Interface.Presentation.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Interface.Presentation.Controllers
{
    public class HomeController : Controller
    {
        private IUserService userService;

        public HomeController()
        {
            userService = UserServiceInjection.Create();
        }

        public HomeController(IUserService userService)
        {
            this.userService = userService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult SignIn()
        {
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Contact()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Documentation()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewRegister(RegisterUserViewModel userModel)
        {
            if (ModelState.IsValid)
            {
                BugTracker.Domain.Entity.User userFound = userService.FindByEmail(userModel.Email);

                if (userFound != null)
                {
                    if (userFound.Password != null)
                    {
                        ModelState.AddModelError("INVALID_USER", "Email is already in use");
                        return View("Register");
                    }
                    else
                    {
                        ModelState.AddModelError("INVALID_USER", "Email is used with github, you can set a password in your perfil settings");
                        return View("Register");
                    }
                }
                else
                {
                    string fileName = "default-perfil.jpg";

                    if (userModel.FileImage != null)
                    {
                        fileName = UploadImageService.UploadUserImage(userModel.FileImage);
                    }

                    BugTracker.Domain.Entity.User user = new User(
                        userModel.Name,
                        userModel.Email,
                        userModel.Password,
                        fileName,
                        Guid.NewGuid().ToString() + new Random().Next(1000),
                        null,
                        true,
                        false);

                    user = userService.Add(user);

                    UserActivationMail.SendTo(user);
                }
            }
            else
            {
            return View("register");
            }
            return RedirectToAction("Index","Login");
        }
        
    }
}

Src/BugTracker/Interface.Presentation/Controllers/SendEmailController.cs
using Interface.Presentation.Mail_Body;
using Interface.Presentation.Models.Email;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Interface.Presentation.Controllers
{
    public class SendEmailController : Controller
    {
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Send(SendEmailModel emailModel)
        {
            if(ModelState.IsValid)
                SendEmailToBugtracker.SendEmail(emailModel);
            return RedirectToAction("Index","Home");
        }
    }
}

Src/BugTracker/Interface.Presentation/Views/Home/contact.cshtml
@model Interface.Presentation.Models.Email.SendEmailModel

@{
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
    ViewBag.Title = "Contact";
}


<section class="no-margin">
    <iframe width="100%" height="200" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3462.4025418409483!2d-51.148697884446925!3d-29.794912826676413!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x951968e7b4ed7db9%3A0x35f6f8838a65a91b!2sCWI+Software!5e0!3m2!1sen!2sbr!4v1467437217015"></iframe>
</section>
<section id="contact-page" class="container">
    <div class="row-fluid">
        <div class="span8">
            <h4>Contact Form</h4>
            <div class="status alert alert-success" style="display: none"></div>
            @using (Html.BeginForm("Send", "SendEmail", FormMethod.Post, new { @class = "contact-form", name = "contact-form", id = "main-contact-form" }))
            {
                @Html.AntiForgeryToken()
                <div class="row-fluid">
                    <div class="span5">

                        @Html.LabelFor(model => model.FirstName)
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "input-block-level", placeholder = "Your First Name" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })

                        @Html.LabelFor(model => model.LastName)
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "input-block-level", placeholder = "Your Last Name" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })

                        @Html.LabelFor(model => model.Email)
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "input-block-level", placeholder = "Your Email Address" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                    <div class="span7">
                        @Html.LabelFor(model => model.Message)
                        @Html.TextAreaFor(model => model.Message, new { style = "resize:none", name = "message", id = "message", @class = "input-block-level", rows = "8" })
                        @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
                    </div>
                </div>
                <input type="submit" class="btn btn-primary btn-large pull-right" value="Send Message" />
            }
        </div>
        <div class="span3" id="b-contact">
            <h4>Our Address</h4>
            <p>Av. Theodomiro Pôrto da Fonseca.</p>

            <p>
                <i class="icon-map-marker pull-left"></i> 3101 - Cristo Rei, São Leopoldo<br>
                RS, 09075-056,  Brazil
            </p>
            <p>
                <i class="icon-envelope"></i> &nbsp;crescer.bugtracker@gmail.com
            </p>
            <p>
                <i class="icon-phone"></i> &nbsp;+55 51 9999 9999
            </p>
        </div>
    </div>
</section>
<!--Bottom-->

Src/BugTracker/Interface.Presentation/Views/Home/documentation.cshtml
@{
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
    ViewBag.Title = "Documentation";
}

@section css{
    @Styles.Render("~/Content/documentation")
}

<div class="container main">
    <div class="row-fluid">
        <aside class="span4 doc-top-margin" id="doc-sidebar">
            <div class="widget">
                <h2>Welcome</h2>
                <div class="widget-blog-items">
                    <div class="media">
                        <div>
                            <span class="span1 list-item">
                                <i class="fa fa-file-text-o" aria-hidden="true"></i>
                            </span>
                            <span class="span11 list-link">
                                <a href="#first-step" class="link-item">First Step</a>
                            </span>
                        </div>
                        <div>
                            <span class="span1 list-item">
                                <i class="fa fa-file-text-o" aria-hidden="true"></i>
                            </span>
                            <span class="span11 list-link">
                                <a href="#dowloading" class="link-item">Downloading</a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="widget">
                <h2>Installation</h2>
                <div class="widget-blog-items">
                    <div class="media">
                        <div>
                            <span class="span1 list-item">
                                <i class="fa fa-file-text-o" aria-hidden="true"></i>
                            </span>
                            <span class="span11 list-link">
                                <a href="#requirements" class="link-item">Requirements</a>
                            </span>
                        </div>
                        <div>
                            <span class="span1 list-item">
                                <i class="fa fa-file-text-o" aria-hidden="true"></i>
                            </span>
                            <span class="span11 list-link">
                                <a href="#install" class="link-item">How to install</a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="widget">
                <h2>How To Use</h2>
                <div class="widget-blog-items">
                    <div class="media">
                        <div>
                            <span class="span1 list-item">
                                <i class="fa fa-file-text-o" aria-hidden="true"></i>
                            </span>
                            <span class="span11 list-link">
                                <a href="#tracking" class="link-item">Tracking bugs</a>
                            </span>
                        </div>
                        <div>
                            <span class="span1 list-item">
                                <i class="fa fa-file-text-o" aria-hidden="true"></i>
                            </span>
                            <span class="span11 list-link">
                                <a href="#errors" class="link-item">Errors</a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </aside>
        <div class="span8">
            <div>
                <h1 class="doc-heading doc-top-margin">Welcome</h1><hr>
                <div class="doc-article" id="first-step">
                    <h2>First Step</h2>
                    <p>The first step to start using our service is making an account. You will be able then to access the panel and from there you will see all reports of your applications.</p>
                </div>
                <div class="doc-article" id="downloading">
                    <h2>Downloading</h2>
                    <p>The download of the library will be avalible in your panel on the download tab and you only need to include it in your application.</p>
                </div>
            </div>

            <div>
                <h1 class="doc-heading">Installation</h1><hr>
                <div class="doc-article" id="requirements">
                    <h2>Requirements</h2>
                    <p>To use the library it is extremely essecial that you have jquery in your application, otherwise BugTracker's library will not work. It is possible to download jquery <a href="http://jquery.com/download" target="_blank">here</a></p>
                </div>
                <div class="doc-article" id="install">
                    <h2>How to install</h2>
                    <p>First you download the library that will be avalible in your panel on the download tab. You need to include it in your application and remember, it is very important to use the library that you downloaded in your account because after you have created it you will have an identifier and when you download it comes together with the library.</p>
                </div>
            </div>

            <div>
                <h1 class="doc-heading">How To Use</h1><hr>
                <div class="doc-article" id="tracking">
                    <h2>Tracking bugs</h2>
                    <div>
                        <pre class="code">
Exemple of using

    CWITracker.track({

        Trace: e //exception object ,
        Status: CWITracker.ERROR,
        Tags: ["critical"]

    }, function callback(error, success) {
        console.log(error || success)
    });
                        </pre>
                        <h3><b>Params:</b></h3><br>

                        <h4><b>*Object:</b></h4><br>

                        <p>
                            Status: Error Status. { ERROR, INFO or WARNING }<br>
                            Tags: String array informing the tags to use as filter searching. You also can use a tag master here to send email for yourself.<br>
                            Trace: Any object.
                        </p><br><br>


                        <h4><b>*Function callback:</b></h4><br>

                        <p>function to be performed after the error was tracked.</p><br>

                        <p>
                            - First param: A string reporting the error description or undefined in case of success.<br>
                            - Second param: A string reporting success of undefined in case of error.<br><br>

                            <b>OBS: Both object and function callback are required.</b>
                        </p>
                    </div>
                </div>
                <div class="doc-article" id="errors">
                    <h3><b>Errors</b></h3><br>
                    <h4><b>Using the library you can have some errors</b></h4><br><br>


                    <p><b>"Domain invalid or Libray broke. Verify your domain in painel and download again library."</b><br>
                    It happens when the host request is different of the one stored in the applications panel or if the library is corrupted. In this situation check if the "Url" field is correct and then download again the library
                    <br><br>
                    <b>"Tags exceeded limit 20 characters":</b><br>
                    You sent tags exceeding the limit of 20 characters.</p>
                </div>
            </div>
        </div>

    </div>
</div>

Src/BugTracker/Interface.Presentation/Views/Home/index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
    ViewBag.Title = "Home";
}

@section css{
    @Styles.Render("~/Content/slideSL")
}

<!--Slider-->
<section id="slide-show">
    <div id="slider" class="sl-slider-wrapper">
        <!--Slider Items-->
        <div class="sl-slider">
            <!--Slider Item1-->
            <div class="sl-slide item3" data-orientation="horizontal" data-slice1-rotation="-25" data-slice2-rotation="-25" data-slice1-scale="2" data-slice2-scale="2">
                <div class="sl-slide-inner">
                    <div class="container">
                        <img class="pull-right" src="~/Content/Images/WebSite/slider/img3.png" alt="" />
                        <h2>Unique Solutions</h2>
                        <h3 class="gap">We already support all devices screens</h3>
                        <a class="btn btn-large btn-transparent" href=@Url.Action("Register", "Home")>Register</a>
                    </div>
                </div>
            </div>
            <!--/Slider Item1-->
            <!--Slider Item2-->
            <div class="sl-slide item2" data-orientation="vertical" data-slice1-rotation="10" data-slice2-rotation="-15" data-slice1-scale="1.5" data-slice2-scale="1.5">
                <div class="sl-slide-inner">
                    <div class="container">
                        <img class="pull-right" src="~/Content/Images/WebSite/slider/img2.png" alt="" />
                        <h2>Planning &amp; Analysis</h2>
                        <h3 class="gap">We have all infrastructure to keep it safe</h3>
                        <a class="btn btn-large btn-transparent" href=@Url.Action("Register", "Home")>Register</a>
                    </div>
                </div>
            </div>
            <!--Slider Item2-->
            <!--Slider Item3-->
            <div class="sl-slide item1" data-orientation="horizontal" data-slice1-rotation="3" data-slice2-rotation="3" data-slice1-scale="2" data-slice2-scale="1">
                <div class="sl-slide-inner">
                    <div class="container">
                        <img src="~/Content/Images/WebSite/logo.png" id="logo-slider" />
                        <img class="pull-right" src="~/Content/Images/WebSite/slider/img1.png" alt="" />
                        <h2>Creative Ideas</h2>
                        <h3 class="gap">We always keep everything updated</h3>
                        <a class="btn btn-large btn-transparent" href=@Url.Action("Documentation", "Home")>Documentation</a>
                    </div>
                </div>
            </div>
            <!--Slider Item3-->
        </div>
        <!--/Slider Items-->
        <!--Slider Next Prev button-->
        <nav id="nav-arrows" class="nav-arrows">
            <span class="nav-arrow-prev"><i class="icon-angle-left fa fa-angle-left"></i></span>
            <span class="nav-arrow-next"><i class="icon-angle-right fa fa-angle-right"></i></span>
        </nav>
        <!--/Slider Next Prev button-->
    </div>
    <!-- /slider-wrapper -->
</section>
<!--/Slider-->

<section class="main-info">
    <div class="container">
        <div class="row-fluid">
            <div class="span9">
                <h4>Do try, do enjoy and do not pay</h4>
                <p class="no-margin">Our service is totally free and safe, you just need to create an account</p>
            </div>
            <div class="span3" id="reg-button">
                <a class="btn btn-success btn-large pull-right" href=@Url.Action("Register", "Home")>Register now</a>
            </div>
        </div>
    </div>
</section>
<!--Services-->
<section id="services">
    <div class="container">
        <div class="center gap">
            <h3>What We Offer</h3>
            <p class="lead">Look at some of our services and what it can do</p>
        </div>
        <div class="row-fluid">
            <div class="span4">
                <div class="media">
                    <div class="pull-left">
                        <i class="icon-globe icon-medium fa fa-info"></i>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">Our service</h4>
                        <p>BugTracker is basically a tracker of bugs that you will use in your website to provide your clients better experiences and it is really easy to include in your website application, check it out !</p>
                    </div>
                </div>
            </div>
            <div class="span4">
                <div class="media">
                    <div class="pull-left">
                        <i class="icon-globe icon-medium fa fa-globe"></i>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">How does it work</h4>
                        <p>You create an account for free in our website and register your website host. You can have up to 5 applications registered and you will be able to download our library to use in your website and what you need to do is use tags where your application can have bugs.</p>
                    </div>
                </div>
            </div>
            <div class="span4">
                <div class="media">
                    <div class="pull-left">
                        <i class="icon-globe icon-medium fa fa-lock"></i>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">Safe</h4>
                        <p>You will recive a library to use in your website application and it will be unique for you. All personal information are encrypted with the best tecnology avalible so do not worry about information leakage, we are fully prepared to keep it safe.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="gap"></div>
        <div class="row-fluid">
            <div class="span4">
                <div class="media">
                    <div class="pull-left">
                        <i class="icon-thumbs-up-alt icon-medium fa fa-thumbs-up"></i>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">Improvement</h4>
                        <p>We are always testing and improving for better quality to make the best traker for your application. Using our service you can see what is the bug, what happened, when, where and how.</p>
                    </div>
                </div>
            </div>
            <div class="span4">
                <div class="media">
                    <div class="pull-left">
                        <i class="icon-leaf icon-medium icon-rounded fa fa-leaf"></i>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">Emails</h4>
                        <p>You can choose a special tag an use it in your application to send an email to yourself and then you will know right away when the bug happens.</p>
                    </div>
                </div>
            </div>
            <div class="span4">
                <div class="media">
                    <div class="pull-left">
                        <i class="icon-shopping-cart icon-medium fa fa-shopping-cart"></i>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">Better sales</h4>
                        <p>It is proved that using our service you will know all the bugs you have to fix and thus you will provide the best experience to your clients as possible.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--/Services-->
<!--Footer-->
<footer id="footer">
    <div class="container">
        <div class="row-fluid">
            <div class="span5 cp">
                &copy; 2016 BugTracker. All Rights Reserved.
            </div>
            <!--/Copyright-->
            <div class="span1 pull-right">
                <a id="gototop" class="gototop pull-right" href="#"><i class="icon-angle-up fa fa-angle-up"></i></a>
            </div>
            <!--/Goto Top-->
        </div>
    </div>
</footer>
<!--/Footer-->


@section scripts{
    @Scripts.Render("~/bundles/slider-sl")
}

Src/BugTracker/Interface.Presentation/Views/Home/register.cshtml
@model Interface.Presentation.Models.User.RegisterUserViewModel

@{
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
    ViewBag.Title = "BugTracker Register";
}

@section css{
    @Styles.Render("~/Content/forms")
}

@using (Html.BeginForm("NewRegister", "Home", FormMethod.Post, new { @class = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Make your register bellow</h3>
            </div>
            <div class="panel-body">
                <div class="row register-column">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Your Full Name" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Your Email Address" } })
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", placeholder = "Password" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control", placeholder = "Confirm Your Password" } })
                            </div>
                        </div>

                    </div>
                    <div class="form-register-new">
                        <label class="btn btn-info btn-file">
                            You can choose now your perfil image or you can add later
                            @Html.TextBoxFor(model => model.FileImage, new { type = "file", style = "display:none;", id = "imgInput" })
                        </label>
                        <input type="submit" value="Create" class="btn btn-success btn-create" />
                    </div>

                </div>
                <div id="project-img" style="display:none">
                    <img id="imgShow" />
                </div>
            </div>
        </div>
    </div>
}