Src/BugTracker/Interface.Presentation/Controllers/LoginController.cs
using BugTracker.Domain.Entity;
using BugTracker.Domain.Interface.Service;
using Interface.Presentation.Filters;
using Interface.Presentation.Models.User;
using Interface.Presentation.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Interface.Presentation.Controllers
{
    public class LoginController : Controller
    {
        IUserService userService;

        public LoginController(IUserService userService)
        {
            this.userService = userService;
        }

        public LoginController()
        {
            userService = UserServiceInjection.Create();
        }

        [HttpGet]
        public ActionResult Index()
        {
            if (UserSessionService.IsLogged)
                return RedirectToAction("Index", "Home");
            return View();
        }

        [HttpGet]
        [UserToken]
        public ActionResult Loggout()
        {
            UserSessionService.Loggout();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignIn(UserLoginViewModel userLoginViewModel)
        {
            if (ModelState.IsValid)
            {
                User userFounded =
                    userService.FindByAuthentication(
                            userLoginViewModel.Email, userLoginViewModel.Password
                        );

                if (userFounded != null)
                {
                    if (!userFounded.AccountConfirmed)
                    {
                        ModelState.AddModelError("INVALID_USER", "Please active your account, an e-mail has been sent to your inbox");

                        return View("Index", userLoginViewModel);
                    }
                    var userLoggedModel = new LoggedUserViewModel(userFounded);

                    UserSessionService.CreateSession(userLoggedModel);
                    return RedirectToAction("Index", "User");
                }
                else
                {
                    ModelState.AddModelError("INVALID_USER", "Email or password is invalid");
                }
            }

            return View("Index", userLoginViewModel);
        }
    }
}

Src/BugTracker/Interface.Presentation/Controllers/LoginGitHubController.cs
using BugTracker.Domain.Interface.Service;
using Interface.Presentation.Services;
using Octokit;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Interface.Presentation.Controllers
{
    public class LoginGitHubController : Controller
    {
        const string clientId = "d6fe6834f30081cf609d";
        private const string clientSecret = "d829abc7d3a9435cdae06599d698106f9066420d";

        IUserService userService = UserServiceInjection.Create();

        readonly GitHubClient client = new GitHubClient(
            new ProductHeaderValue("BugTracker-GitHub-Oauth"), 
            new Uri("https://github.com/"));

        [HttpGet]
        public async Task<ActionResult> GithubAuthentication(string code, string state)
        {
            if (!String.IsNullOrEmpty(code))
            {
                var expectedState = Session["CSRF:State"] as string;
                //TODO: Tratar erro de segurança
                if (state != expectedState) throw new InvalidOperationException("SECURITY FAIL!");
                Session["CSRF:State"] = null;

                var token = await client.Oauth.CreateAccessToken(
                    new OauthTokenRequest(clientId, clientSecret, code)
                    {
                        RedirectUri = new Uri("http://localhost:58173/logingithub/githubauthentication")
                    });
                Session["OAuthToken"] = token.AccessToken;
            }

            return RedirectToAction("SignInGitHub");
        }

        [HttpGet]
        public async Task<ActionResult> SignInGitHub()
        {
            var accessToken = Session["OAuthToken"] as string;

            if (accessToken != null)
            {
                client.Credentials = new Credentials(accessToken);
            }

            try
            {
                var email = await client.User.Email.GetAll();

                string primaryEmail = email.FirstOrDefault(e => e.Primary == true).Email;

                var gitHubUser = await client.User.Current();

                string name = gitHubUser.Name != null ? gitHubUser.Name : gitHubUser.Login;

                string profileImage = DownloadImageService.DownloadUserImage(gitHubUser.AvatarUrl,gitHubUser.Login);

                BugTracker.Domain.Entity.User userFound = userService.FindByEmail(primaryEmail);

                if (userFound == null)
                {
                    userFound = userService.Add(new BugTracker.Domain.Entity.User(
                            name,
                            primaryEmail,
                            null,
                            profileImage,
                            Guid.NewGuid().ToString() + new Random().Next(100).ToString(),
                            null,
                            true,
                            true

                        ));
                }

                UserSessionService.CreateSession(new Models.User.LoggedUserViewModel(userFound));

                return RedirectToAction("Index","User");

            }

            catch (AuthorizationException)
            {
                return Redirect(GetOauthLoginUrl());
            }
        }

        private string GetOauthLoginUrl()
        {
            string csrf = Membership.GeneratePassword(24, 1);
            Session["CSRF:State"] = csrf;

            var request = new OauthLoginRequest(clientId)
            {
                Scopes = { "user", "email" },
                State = csrf
            };
            var oauthLoginUrl = client.Oauth.GetGitHubLoginUrl(request);
            return oauthLoginUrl.ToString();
        }
    }
}

Src/BugTracker/Interface.Presentation/Controllers/UserRecoveryController.cs
using BugTracker.Domain.Entity;
using BugTracker.Domain.Interface.Service;
using BugTracker.Domain.Service;
using Interface.Presentation.Mail_Body;
using Interface.Presentation.Models.UserRecovery;
using Interface.Presentation.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Interface.Presentation.Controllers
{
    public class UserRecoveryController : Controller
    {
        IUserRecoveryService userRecoveryService;
        IUserService userService;

        public UserRecoveryController()
        {
            userRecoveryService = UserRecoveryServiceInjection.Create();
            userService = UserServiceInjection.Create();
        }

        [HttpPost]
        public ActionResult NewPassword(UserRecoveryViewModel userModel)
        {
            if (ModelState.IsValid)
            {
                ForgotPassword userRecovery = userRecoveryService.FindByCode(userModel.IDCode);

                if (userRecovery != null)
                {
                    userService.UpdatePassword(userRecovery.RequestUser, userModel.Password);

                    TempData["Message"] = "Your passwor has been changed with success, try to login";
                }
                return RedirectToAction("Index", "Login");
            }
            return View("NewPassword", userModel);
        }

        [HttpGet]
        public ActionResult ForgotPassword()
        {
            return View("ForgotPassword");
        }

        [HttpPost]
        public ActionResult ForgotPassword(string email)
        {
            var user = userService.FindByEmail(email);

            if (user != null)
            {
                UserRecoverPasswordMail.SendTo(user);

                TempData["Message"] = "You will receive an email to change your password in a few minutes";
            }

            else
            {
                TempData["Message"] = "This email is not registred in our website";
            }

            return View("ForgotPassword");
        }

        [HttpGet]
        public ActionResult Code(string code)
        {
            ForgotPassword userRecovery = userRecoveryService.FindByCode(code);

            if (userRecovery != null)
            {
                var model = new UserRecoveryViewModel() { IDCode = code };
                return View("NewPassword", model);
            }

            TempData["Message"] = "This link is no longer avalible";

            return RedirectToAction("Index", "Login");
        }
    }
}

Src/BugTracker/Interface.Presentation/Views/Shared/NotFound.cshtml

@{
    ViewBag.Title = "NotFound";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<section id="error" class="container">
    <h1>404, Page not found</h1>
    <p>The Page you are looking for doesn't exist.</p>
    <a class="btn btn-success" href=@Url.Action("Index","Home")>GO BACK TO THE HOMEPAGE</a>
</section>

Src/BugTracker/Interface.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    <link rel="shortcut icon" href="~/Content/Images/Application/cockroach.png" type="image/x-icon" />
    @Styles.Render("~/Content/layout")
    @RenderSection("css", false)
</head>
<body class="home">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="col-md-7">
            <nav class="navbar-default pull-left">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="offcanvas" data-target="#side-menu" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
            </nav>
            <div class="search hidden-xs banner-top">
                <a href=@Url.Action("Index", "User")><img src="~/content/images/website/banner-top.png" class="logo" /></a>
            </div>
        </div>
        <div class="col-md-5">
            <div class="header-rightside">

                <ul class="list-inline header-top pull-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            @{
                                var imgPerfil = "~/content/images/user/" + Interface.Presentation.Services.UserSessionService.LoggedUser.Image;
                            }
                            <img src="@Url.Content(imgPerfil)" alt="user" id="user-image">
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <div class="navbar-content">
                                    <span>@Interface.Presentation.Services.UserSessionService.LoggedUser.Name</span>
                                    <p class="text-muted small">
                                        @Interface.Presentation.Services.UserSessionService.LoggedUser.Email
                                    </p>
                                    <div class="divider">
                                    </div>
                                    <a href=@Url.Action("Loggout", "Login") class="view btn-sm active">Loggout</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid display-table">
        <div class="row display-table-row">
            <div class="col-md-2 col-sm-1 display-table-cell v-align box" id="navigation">
                <div class="navi">
                    <ul>
                        <li class="link" data-target-id="Home"><a href=@Url.Action("", "User")><i class="fa fa-home" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Home</span></a></li>
                        <li class="link" data-target-id="Donwload"><a href=@Url.Action("Download", "User")><i class="fa fa-download" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Download</span></a></li class="link">
                        <li class="link" data-target-id="Doceument"><a href=@Url.Action("Documentation", "Home") target="_blank"><i class="fa fa-book" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Documentation</span></a></li>
                        <li class="link" data-target-id="Account"><a href=@Url.Action("Account", "User")><i class="fa fa-user" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Profile</span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10 col-sm-11 display-table-cell v-align">
                <div class="user-dashboard">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/layout")
    @RenderSection("scripts", false)
</body>
</html>

Src/BugTracker/Interface.Presentation/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <title>@ViewBag.Title</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    <link rel="shortcut icon" href="~/Content/Images/Application/cockroach.png" type="image/x-icon" />
    @Styles.Render("~/Content/layout-home")
    @RenderSection("css", false)

</head>
<body>
    <!--Header-->
    <header class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <a id="logo" class="pull-left" href=@Url.Action("Index", "Home")><img src="~/Content/Images/WebSite/banner-top.png" /></a>
            <div class="pull-right navigation-bar">
                <ul class="nav">
                    <li class="nav-link" data-target-id="Home"><a href=@Url.Action("Index", "Home")>Home</a></li>
                    <li class="nav-link" data-target-id="Documentation"><a href=@Url.Action("Documentation", "Home")>Documentation</a></li>
                </ul>
                <ul class="nav">
                    <li class="nav-link" data-target-id="MyPanel"><a href=@Url.Action("Index", "User")>My Panel</a></li>
                    <li class="nav-link" data-target-id="Contact"><a href=@Url.Action("Contact", "Home")>Contact</a></li>
                    <li class="login">
                        <a data-toggle="modal" href="#loginForm"><i class="icon-lock fa fa-sign-in" aria-hidden="true"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </header>
    <!-- /header -->

    <div>
        <div class="alert alert-info" id="informations">
            @TempData["Message"]
        </div>
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })

        @RenderBody()

    </div>

    @Html.Partial("_Login")

    @Scripts.Render("~/bundles/layout-home")

    @RenderSection("scripts", false)
</body>
</html>

Src/BugTracker/Interface.Presentation/Views/Shared/_Login.cshtml
<!--  Login form -->
<div class="modal hide fade in" id="loginForm" aria-hidden="false">
    <div class="modal-header">
        <i class="icon-remove fa fa-times" data-dismiss="modal" aria-hidden="true"></i>
        <h4>SignIn Bellow</h4>
    </div>
    <!--Modal Body-->
    <div class="modal-body">
        @using (Html.BeginForm("SignIn", "Login", FormMethod.Post, new { @class = "form-inline", id = "form-login" }))
            {
            @Html.AntiForgeryToken()

            <input type="email" name="email" class = "input-small input-email", placeholder = "E-mail" />

            <input type="password" id="input-password" name="password" class = "input-small", placeholder = "Password" />

            <button type="submit" class="btn btn-info" id="btn-sign-in">Sign in</button>
        }
        <a href=@Url.Action("SignInGitHub","LoginGitHub") class="btn btn-success">GitHub</a>
        <a href=@Url.Action("Register", "Home") class="btn btn-warning">Register</a>
        <a href=@Url.Action("ForgotPassword","UserRecovery")>Forgot your password?</a>
    </div>
    <!--/Modal Body-->
</div>
<!--  /Login form -->