Src/BugTracker/Interface.Presentation/Models/Application/ApplicationAndBugsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain = BugTracker.Domain.Entity;

namespace Interface.Presentation.Models.Application
{
    public class ApplicationAndBugsViewModel
    {
        public String AppName { get; set; }
        public int AppId { get; set; }
        public String AppImage { get; set; }
        public Domain.BugTracker Bug{ get; set; }
        public int TracksCountError { get; set; }
        public int TracksCountWarning { get; set; }
       

        public ApplicationAndBugsViewModel(int appId, String appName, String appImg, Domain.BugTracker bug, int countError, int countWarning)
        {
            this.AppName = appName;
            this.AppId = appId;
            this.AppImage = appImg;
            this.Bug = bug;
            this.TracksCountError = countError;
            this.TracksCountWarning = countWarning;
        }
    }
}

Src/BugTracker/Interface.Presentation/Models/Application/ApplicationModel.cs
using Interface.Presentation.Filters;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Interface.Presentation.Models
{
    public class ApplicationModel
    {
        public int? Id { get; set; }

        [Required(ErrorMessage = "Title is required")]
        [DisplayName("Title")]
        [StringLength(50, ErrorMessage = "Maximun of 50 characters")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Description is required")]
        [DisplayName("Description")]
        [StringLength(100, ErrorMessage = "Maximun of 100 characters")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Url application is required")]
        [DisplayName("Url Application")]
        [StringLength(100, ErrorMessage = "Maximun of 100 characters")]
        public string Url { get; set; }
        
        [DisplayName("Icon Application")]
        [StringLength(100, ErrorMessage = "Maximun of 100 characters")]
        public string Icon { get; set; }

        [Required(ErrorMessage ="Special tag error is required")]
        [DisplayName("Special Tag Error")]
        [StringLength(20,ErrorMessage = "Maximun of 20 characters")]
        public string Tag { get; set; }

        
        [DisplayName("Icon Application")]
        [ImageExtensionValidation(ErrorMessage = "Only images .jpg, .jpeg and .png")]
        [FileSizeValidation(100 * 1024, ErrorMessage = "File size must be lesser than 100 kb")]
        public HttpPostedFileBase File { get; set; }

       
    }
}

Src/BugTracker/Interface.Presentation/Models/Application/ApplicationViewModel.cs
using Interface.Presentation.Models.User;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using Domain = BugTracker.Domain.Entity;

namespace Interface.Presentation.Models.Application
{
    public class ApplicationViewModel
    {
        public int IDApplication { get; private set; }
        public String Title { get; private set; }
        public String Description { get; private set; }
        public String Url { get; private set; }
        public String Image { get; private set; }
        public String SpecialTag { get; private set; }
        public LoggedUserViewModel User { get; private set; }

        public ApplicationViewModel(int idApplication,String title,String description,String url,String image,String specialTag,LoggedUserViewModel user)
        {
            this.IDApplication = idApplication;
            this.Title = title;
            this.Description = description;
            this.Url = url;
            this.Image = image;
            this.SpecialTag = specialTag;
            this.User = user;
        }

        public ApplicationViewModel(Domain.Application app) : 
            this(app.IDApplication,app.Title,app.Description,app.Url,app.Image,app.SpecialTag,new LoggedUserViewModel(app.User)) {  }

        public static ICollection<ApplicationViewModel> CollectionToViewModel(ICollection<Domain.Application> list)
        {
            ICollection<ApplicationViewModel> appModel = new Collection<ApplicationViewModel>();

            //TODO: Fazer com linq
            foreach (Domain.Application app in list)
            {
                appModel.Add(new ApplicationViewModel(app));
            }

            return appModel;
        }
    }
}

Src/BugTracker/Interface.Presentation/Controllers/ApplicationController.cs
using BugTracker.Domain.Entity;
using BugTracker.Domain.Interface.Service;
using BugTracker.Domain.Service;
using Interface.Presentation.Filters;
using Interface.Presentation.Models;
using Interface.Presentation.Models.Application;
using Interface.Presentation.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Interface.Presentation.Controllers
{
    public class ApplicationController : Controller
    {
        private IApplicationService applicationService;
        private IUserService userService;
        

        public ApplicationController()
        {
            applicationService = ApplicationServiceInjection.Create();
            userService = UserServiceInjection.Create();
        }

        public ApplicationController(ApplicationService appService, UserService userService)
        {
            this.applicationService = appService;
            this.userService = userService;
        }

        [UserToken]
        [HttpGet]
        public ActionResult RegisterApp(int? id)
        {
            if (id.HasValue)
            {
                var app = applicationService.FindById((int)id);
                var model = new ApplicationModel();
                model.Id = app.IDApplication;
                model.Title = app.Title;
                model.Url = app.Url;
                model.Description = app.Description;
                model.Icon = app.Image;

                model.Tag = app.SpecialTag;

                return View("register-app", model);
            }

            return View("register-app");
        }

        [HttpPost]
        [UserToken]
        [ValidateAntiForgeryToken]
        public ActionResult NewEditApp(ApplicationModel model)
        {
            if (ModelState.IsValid)
            {
                var idUser = UserSessionService.LoggedUser.IDUser;
                var user = userService.FindById(idUser);
                var application = applicationService.FindByIDUser(idUser);

                String fileName = model.File != null ? model.File.FileName : "application-default.png";


                if (model.Id.HasValue)
                {
                    if (model.File == null)
                    {
                        fileName = model.Icon;
                    }
                    else
                    {
                        fileName = UploadImageService.UploadApplicationImage(model.File);
                    }

                    var app = new Application(model.Id.Value, model.Title, model.Description,
                                            model.Url, true, fileName,
                                            model.Tag, idUser, user);
                    applicationService.Edit(app);
                    return RedirectToAction("index", "user");
                }
                else
                {
                    if (application.Count() < 5)
                    {
                        if (application.FirstOrDefault(a => a.Url.Equals(model.Url)) == null)
                        {
                            if (model.File != null)
                            {
                                fileName = UploadImageService.UploadApplicationImage(model.File);
                            }
                            var app = new Application(model.Title, model.Description,
                                                    model.Url, true, fileName,
                                                    model.Tag, idUser, user);
                            applicationService.Add(app);
                            return RedirectToAction("index", "user");
                        }
                        else
                        {
                            ModelState.AddModelError("INVALID_URL", "This  url already exist");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("INVALID_APPLICATION_NUMBER", "The limit of applications you can have is 5");
                    }

                }

            }

            return View("register-app", model);
        }

        [UserToken]
        [HttpGet]
        public ActionResult DeleteApp(int id)
        {
            var app = applicationService.FindById(id);
            if (app != null)
            {
                var user = userService.FindById(app.IDUser);

                var appToDelete = new Application(app.IDApplication, app.Title, app.Description, app.Url, false, app.Image, app.SpecialTag, app.IDUser, user);
                applicationService.Edit(appToDelete);
            }

            return RedirectToAction("Index", "User");
        }

        [UserToken]
        [HttpGet]
        public ActionResult DetailsApp(int id)
        {
            var app = applicationService.FindById(id);

            if (app.IDUser != UserSessionService.LoggedUser.IDUser)
            {
                return RedirectToAction("Index", "User");
            }

            ViewBag.Status = Enum.GetNames(typeof(BugTracker.Domain.Entity.BugTrackerStatus));

            return View("details", app);
        }
    }
}

Src/BugTracker/Interface.Presentation/Controllers/BugTrackerController.cs
using BugTracker.Domain.Entity;
using BugTracker.Domain.Interface.Service;
using Interface.Presentation.App_Start;
using Interface.Presentation.Extensions;
using Interface.Presentation.Filters;
using Interface.Presentation.Mail_Body;
using Interface.Presentation.Models.BugTracker;
using Interface.Presentation.Services;
using iTextSharp.text.pdf;
using iTextSharp.xmp;
using System.IO;
using System.Web.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Domain = BugTracker.Domain;
using System.Web.UI.HtmlControls;
using iTextSharp.text;
using iTextSharp.text.html.simpleparser;
using iTextSharp.text.pdf.parser;

namespace Interface.Presentation.Controllers
{
    public class BugTrackerController : Controller
    {
        private IBugTrackerService bugTrackerService;
        private IApplicationService applicationService;

        public BugTrackerController()
        {
            bugTrackerService = BugTrackerServiceInjection.Create();
            applicationService = ApplicationServiceInjection.Create();
        }

        public BugTrackerController(IBugTrackerService bugTrackerService, IApplicationService applicationService)
        {
            this.bugTrackerService = bugTrackerService;
            this.applicationService = applicationService;
        }

        [HttpPost]
        [AllowOriginAttributeConfig]
        public JsonResult Add(BugTrackerPostModel bugTrackerPostModel)
        {
            var request = HttpContext.Request;
            JsonResult returnJson;

            var application =
                applicationService.FindByUrlAndUserHashCode(
                HttpContext.Request.UrlReferrer.Host,
                    bugTrackerPostModel.HashCode
                 );

            if (!ModelState.IsValid)
            {
                HttpContext.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                returnJson = Json(new { error = string.Join("; ", ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage)) });
            }

            if (application == null)
            {
                HttpContext.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                returnJson = Json(new { error = "Domain invalid or Libray broke. Verify your domain in painel and download again library." });
            }
            else
            {
                try
                {
                    var sendEmail = bugTrackerService.Add(
                        new Domain.Entity.BugTracker(
                            application,
                            bugTrackerPostModel.Status,
                            bugTrackerPostModel.Trace,
                            DateTime.Now,
                            bugTrackerPostModel.ToTrackerTag(),
                            new Domain.Entity.Browser(request.Browser.Browser, request.Browser.Version),
                            new Domain.Entity.OperationalSystem(request.Browser.Platform)
                        )
                    );

                    if (sendEmail)
                    {
                        TagMasterMail.SendTo(application.User.Email, application.Title);
                    }

                    returnJson = Json(new { msg = "Success!" });
                }
                catch (Domain.Exceptions.TagVeryLargeException e)
                {
                    HttpContext.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    returnJson = returnJson = Json(new { error = e.ToString() });
                }
                catch (Exception e)
                {
                    HttpContext.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                    returnJson = returnJson = Json(new { error = e.ToString() });
                }
            }
            
            return returnJson;
        }

        [HttpPost]
        public ActionResult GetBugTrackerPaginedByApp(BugTrackerFilter filter)
        {
            var bugTrackers = bugTrackerService.FindByApplicationPagined(filter);

            return PartialView("_bug-trackers-application", bugTrackers.FromModel());
        }

        [HttpPost]
        public JsonResult GetCountBugTrackerByApp(BugTrackerFilter filter)
        {
            return formatReturn(bugTrackerService.GetCountBugsByApp(filter));
        }

        [HttpGet]
        public JsonResult GetGraphicModelByIdApplication(int idApplication)
        {
            return formatReturn(bugTrackerService.GetGraphicModelByIdApplication(idApplication));
        }

        [HttpPost]
        public FileResult ExportBugsForPdf(BugTrackerFilter filter)
        {
            var bugTrackers = bugTrackerService.FindByApplicationFilter(filter);

            Byte[] bytes = ExportFileService.TableHtmlToPdf(bugTrackers).ToArray();

            return File(
                bytes,
                System.Net.Mime.MediaTypeNames.Application.Octet,
                DateTime.Now.ToString("dd_MM/yyyy") + "_bugs.pdf"
            );
        }

        [HttpPost]
        public FileResult ExportBugsForTxt(BugTrackerFilter filter)
        {
            var bugTrackers = bugTrackerService.FindByApplicationFilter(filter);

            Stream streamFile = ExportFileService.TableHtmlToTxt(bugTrackers);



            return File(
                streamFile,
                System.Net.Mime.MediaTypeNames.Application.Octet,
                DateTime.Now.ToString("dd_MM/yyyy") + "_bugs.txt"
            );
        }

        private JsonResult formatReturn(IList<dynamic> data)
        {
            return Json(
                new
                {
                    data = data,
                    status = Enum.GetNames(typeof(Domain.Entity.BugTrackerStatus))
                },
                JsonRequestBehavior.AllowGet
            );
        }

        public static string ExtractTextFromPdf(string path)
        {
            ITextExtractionStrategy its = new iTextSharp.text.pdf.parser.LocationTextExtractionStrategy();

            using (PdfReader reader = new PdfReader(path))
            {
                StringBuilder text = new StringBuilder();

                for (int i = 1; i <= reader.NumberOfPages; i++)
                {
                    string thePage = PdfTextExtractor.GetTextFromPage(reader, i, its);
                    string[] theLines = thePage.Split('\n');
                    foreach (var theLine in theLines)
                    {
                        text.AppendLine(theLine);
                    }
                }
                return text.ToString();
            }
        }
    }
}

Src/BugTracker/Interface.Presentation/Views/Application/details.cshtml
@model BugTracker.Domain.Entity.Application
@{
    ViewBag.Title = "Application Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-success col-md-11 box full-width">
    <div class="panel-heading">
        <h4>Graphics</h4>
    </div>

    <div id="graphics"></div>
</div>

    <div class="panel panel-success col-md-11 box full-width">
        <div class="panel-heading">
            <h4>@Html.DisplayFor(model => model.Title) </h4>
        </div>
        <div class="panel-body">
            <div id="count-bugs" class="text-center"></div>
            <div id="filters">
                <div class="col-md-1"></div>
                <div class="col-md-3">
                    <input type="text" class="form-control" value="@ViewBag.FilterName" name="Trace" id="Trace" placeholder="Trace...">
                </div>

                <div class="col-md-3 status-filter">
                    @{
                        int i = 1;

                        foreach (String s in ViewBag.Status)
                        {
                            <input type="checkbox" id="Status" class="align-input-text" name="Status" checked="checked" value="@i" /> @s
                            i++;
                        }
                    }
                </div>
                <div class="col-md-5">
                    <button id="filter" class="btn btn-success btn-hover-green">Filter</button>
                    <button class="btn btn-success dropdown-toggle btn-hover-green" type="button" id="dropdown-export" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        Export
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu dropdown-export" aria-labelledby="dropdown-export">
                        <li class="text-center">
                            <button class="btn btn-success" type="button" id="convert-to-pdf" data-link="/BugTracker/ExportBugsForPdf"> Pdf </button>
                        </li>
                        <li class="text-center">
                            <button class="btn btn-success" type="button" id="convert-to-txt" data-link="/BugTracker/ExportBugsForTxt"> Txt </button>
                        </li>
                    </ul>
                </div>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th>Trace</th>
                        <th>Status</th>
                        <th>Occurred Date</th>
                        <th>Tags</th>
                        <th>Browser Name</th>
                        <th>Browser Version</th>
                        <th>Operation System</th>
                    </tr>
                </thead>
                <tbody id="list-bug-tracks"></tbody>
            </table>
        </div>
    </div>

@using (Html.BeginForm("ExportBugsForPdf", "BugTracker", FormMethod.Post, new { @class = "export-form", id = "filter-form" }))
{
    @Html.AntiForgeryToken()
    <input type="hidden" name="IdApplication" id="export_idApplication" />
    <input type="hidden" name="Track" id="export_track" />
}

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" id="modal" aria-labelledby="myLargeModalLabel">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">Track details</h4>
            </div>
            <div class="modal-body" id="trace-content">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/application")

    <script>
        var idApplication = '@Model.IDApplication';
        new BugTrackerView().init();
    </script>
}

Src/BugTracker/Interface.Presentation/Views/Application/register-app.cshtml
@model Interface.Presentation.Models.ApplicationModel
@{
    ViewBag.Title = "CreateApp";
}

<div class="panel panel-success col-md-11 box">
    <div class="panel-heading">
        @if (Model != null)
        {
            <h4>Edit application</h4>
        }
        else
        {
            <h4>New application</h4>
        }

    </div>
    @using (Html.BeginForm("NewEditApp", "Application", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Icon)

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Tag, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Tag, new { htmlAttributes = new { @class = "form-control" } })
                </div>

                <div class="col-md-6">
                    <label class="btn btn-info btn-image">
                        You can choose now your application image or you can add later
                        @Html.TextBoxFor(model => model.File, new { type = "file", style = "display:none", id = "imgInput" })
                    </label>
                </div>
            </div>

            <div id="project-img" style="display:none">
                <img id="imgShow" />
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
</div>